apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: projet51
  name: front-app
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: front-app
          image: guigui2515/projet51:front-app
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_REACT_APP_URI
              value: "https://anselmsystem.s-alx-k.com"
